const ACTION_TYPES = {
    API_PENDING: 'API_PENDING',
    API_SUCCESS: 'API_SUCCESS',
    API_ERROR: 'API_ERROR',
    LOGIN_PENDING:'LOGIN_PENDING',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_ERROR:'LOGIN_ERROR',
    PROFILE_REQUEST:'PROFILE_REQUEST',
    PROFILE_SUCCESS:'PROFILE_SUCCESS',
    PROFILE_FAIL:'PROFILE_FAIL',
    CLEAR_STATE:'CLEAR_STATE'
  };
  export default ACTION_TYPES;